service:
  name: serverless-epg-api

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

package:
  exclude:
    - coverage/**
    - .circleci/**

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  deploymentBucket:
    name: api.pencheza.com

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
          cors: true
